"""add rating_change to duels

Revision ID: 3a1efe6da2be
Revises: d9e2106c6066
Create Date: 2026-08-05 08:28:21.724388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1efe6da2be'
down_revision: Union[str, Sequence[str], None] = 'd9e2106c6066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duels', sa.Column('rating_change', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duels', 'rating_change')
    # ### end Alembic commands ###
