# Generated by Django 6.0.3 on 2026-07-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('password_reset', 'Password Reset')], default='password_reset', max_length=20),
        ),
    ]
