# Generated by Django 6.0.3 on 2026-03-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('login', 'Login'), ('password_reset', 'Password Reset')], default='login', max_length=20),
        ),
    ]
