# Generated by Django 6.0.3 on 2026-03-09 10:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_duel_id_alter_otp_id_alter_player_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('playstation', 'PlayStation'), ('xbox', 'Xbox'), ('pc', 'PC'), ('mobile', 'Mobile')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='duel',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='duel',
            name='player2',
        ),
        migrations.AddField(
            model_name='duel',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='challenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='challenges_created', to='src.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duel',
            name='challenger_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='challenger_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='duel',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges_received', to='src.player'),
        ),
        migrations.AddField(
            model_name='duel',
            name='opponent_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='opponent_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='duel',
            name='stake',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='duel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='duel',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duels_won', to='src.player'),
        ),
        migrations.AddField(
            model_name='duel',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='src.game'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MatchEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='src.duel')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.player')),
            ],
        ),
    ]
